src/main/scala/scapi/sigma/DLogProtocol.scala
src/main/scala/sigmastate/interpreter/CostAccumulator.scala
src/main/scala/sigmastate/serialization/ConcreteCollectionSerializer.scala
src/main/scala/sigmastate/serialization/FalseLeafSerializer.scala
src/main/scala/sigmastate/serialization/IntConstantSerializer.scala
src/main/scala/sigmastate/serialization/RelationSerializer.scala
src/main/scala/sigmastate/serialization/STypeSerializer.scala
src/main/scala/sigmastate/serialization/SigmaSerializer.scala
src/main/scala/sigmastate/serialization/SigmaSerializerExample.scala
src/main/scala/sigmastate/serialization/TaggedVariableSerializer.scala
src/main/scala/sigmastate/serialization/TrueLeafSerializer.scala
src/main/scala/sigmastate/serialization/ValueSerializer.scala
src/main/scala/sigmastate/trees.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/utxo/SigmaStateTransaction.scala
src/main/scala/sigmastate/utxo/UtxoContext.scala
src/main/scala/sigmastate/utxo/transformers.scala
src/main/scala/sigmastate/values.scala
src/test/scala/sigmastate/serialization/BooleanLeafsSerializerSpecification.scala
src/test/scala/sigmastate/serialization/ConcreteCollectionSerializerSpecification.scala
src/test/scala/sigmastate/serialization/IntConstantSerializerSpecification.scala
src/test/scala/sigmastate/serialization/RelationSerializerSpecification.scala
src/test/scala/sigmastate/serialization/SerializationSpecification.scala
src/test/scala/sigmastate/serialization/TableSerializationSpecification.scala
src/test/scala/sigmastate/serialization/TaggedVariableSerializerSpecification.scala
src/test/scala/sigmastate/utxo/UtxoInterpreterSpecification.scala
src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala

Each Value can have type descriptor 
```
trait Value[+S <: SType> {
def tpe: S
}
```
Related subtasks:

Type descriptor for each Value

---

src/main/scala/scapi/sigma/DLogProtocol.scala
src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/lang/SigmaPredef.scala
src/main/scala/sigmastate/lang/SigmaPrinter.scala
src/main/scala/sigmastate/lang/SigmaSpecializer.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/lang/Terms.scala
src/main/scala/sigmastate/lang/syntax/Core.scala
src/main/scala/sigmastate/lang/syntax/Exprs.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/utxo/ErgoTransaction.scala
src/main/scala/sigmastate/values.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala
src/test/scala/sigmastate/utxo/UtxoInterpreterSpecification.scala

The following syntax is supported:
```
SELF.R3[Int].value     // access R3 register, cast its value to Int and return it
SELF.R3.isDefined      // check that value of R3  is defined
SELF.R3[Int].isDefined // check that value of R3  is defined and has type Int
```
Note, that Option[T] is introduced at frontend to represent the type of register value
```
SELF.R3: Option[T]   // where T is type variable
SELF.R3[Int]: Option[Int]   
```
However, Option is not supported by `Interpreter`, so all `Option` operations are eliminated by `SigmaSpecializer`

Accessing registers of Box values

---

src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/lang/SigmaSpecializer.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/lang/Types.scala
src/main/scala/sigmastate/serialization/ValueSerializer.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/values.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala

This constructors are implemented throughout all frontend phases up to Specializer.
Currently Speciaizer throws exception when encounter OptionValue node with message "Option values are not supported".
This can be removed after Option is supported in the interpreter.

Preliminary support of Some and None constructors of Option values

---

src/main/scala/scapi/sigma/BcDlogFp.scala
src/main/scala/scapi/sigma/DlogGroup.scala
src/main/scala/scapi/sigma/SigmaProtocolFunctions.scala
src/main/scala/sigmastate/SchnorrSigner.scala
src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/lang/SigmaParser.scala
src/main/scala/sigmastate/lang/SigmaPrinter.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/lang/Types.scala
src/main/scala/sigmastate/lang/syntax/Basic.scala
src/main/scala/sigmastate/lang/syntax/Exprs.scala
src/main/scala/sigmastate/lang/syntax/Identifiers.scala
src/main/scala/sigmastate/lang/syntax/Literals.scala
src/main/scala/sigmastate/serialization/FalseLeafSerializer.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/utils/Extensions.scala
src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
src/test/scala/sigmastate/serialization/TableSerializationSpecification.scala
src/test/scala/sigmastate/serialization/generators/ConcreteCollectionGenerators.scala
src/test/scala/sigmastate/serialization/generators/ValueGeneratots.scala
src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala

Resolves #74 
Forward references in `val` definitions are correct, because method `P` takes by-name argument, which is executed during parsing, not during initializations.

Fix code inspection issues in particular #74

---

src/main/scala/sigmastate/lang/SigmaCompiler.scala
src/main/scala/sigmastate/lang/SigmaSpecializer.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/utils/Helpers.scala
src/main/scala/sigmastate/utxo/ErgoTransaction.scala
src/main/scala/sigmastate/utxo/transformers.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala

Resolves #71 
Implementation of filtering with `arr.where(fun (i: Int) = i > 0)` require recursive reduceToCrypto and corresponding refactoring of reduction process.

Slice and Where operations for Arrays

---

src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/trees.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/utils/Helpers.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala
src/test/scala/sigmastate/utxo/AVLTreeScriptsSpecification.scala
src/test/scala/sigmastate/utxo/ErgoInterpreterSpecification.scala

Fix: Extract collections from registers

---

src/main/scala/org/ergoplatform/ErgoBox.scala
src/main/scala/org/ergoplatform/ErgoTransaction.scala
src/main/scala/org/ergoplatform/Input.scala
src/main/scala/sigmastate/interpreter/Interpreter.scala
src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala
src/test/scala/sigmastate/utxo/SerializationRoundTripSpec.scala

Check/improve test coverage for new serializers added in PR #124. Part 2. 

---

src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/utxo/transformers.scala
src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala

Eliminate implicit parameters in case classes to avoid implementing `equals()`/ `hashCode()`

---

src/main/scala/sigmastate/lang/SigmaSpecializer.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/lang/Terms.scala
src/main/scala/sigmastate/serialization/transformers/ByIndexSerializer.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/utxo/transformers.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala
src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala
src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala

Continue from the #127 
Closes #99
Todo:

Add optional default value to `ByIndex` (new)

---

src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/serialization/TypeSerializer.scala
src/main/scala/sigmastate/types.scala
src/test/scala/sigmastate/serialization/AndSerializerSpecification.scala
src/test/scala/sigmastate/serialization/OrSerializerSpecification.scala
src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala

Close #210 
@ergomorphic Threads we're `Runnable` but stuck. Thread stacks were pointing to `SCollection`  object instantiation. Seems like an issue with constructor not being thread safe. 
As an alternative, we can disable parallel test execution altogether.

Fix parallel test execution in sbt

---

src/main/scala/sigmastate/lang/exceptions/SigmaSerializerExceptions.scala
src/main/scala/sigmastate/serialization/SigmaSerializer.scala
src/main/scala/sigmastate/serialization/TypeSerializer.scala
src/main/scala/sigmastate/serialization/ValueSerializer.scala
src/main/scala/sigmastate/utils/ByteReader.scala
src/main/scala/sigmastate/utils/ByteWriter.scala
src/main/scala/sigmastate/utils/Helpers.scala
src/test/scala/sigmastate/serialization/ConcreteCollectionSerializerSpecification.scala
src/test/scala/sigmastate/serialization/DeserializationResilience.scala
src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala
src/test/scala/sigmastate/utils/ByteReaderWriterImpSpecification.scala

Malicious test suite for deserializer

---

src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/interpreter/Interpreter.scala
src/main/scala/sigmastate/lang/SigmaBuilder.scala
src/main/scala/sigmastate/lang/SigmaParser.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/lang/Terms.scala
src/main/scala/sigmastate/lang/exceptions/SigmaTyperExceptions.scala
src/main/scala/sigmastate/lang/syntax/Literals.scala
src/main/scala/sigmastate/serialization/DataSerializer.scala
src/main/scala/sigmastate/serialization/OpCodes.scala
src/main/scala/sigmastate/serialization/TypeSerializer.scala
src/main/scala/sigmastate/serialization/ValueSerializer.scala
src/main/scala/sigmastate/trees.scala
src/main/scala/sigmastate/types.scala
src/main/scala/sigmastate/utxo/CostTable.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/lang/LangTests.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala
src/test/scala/sigmastate/serialization/ConstantSerializerSpecification.scala
src/test/scala/sigmastate/serialization/DataSerializerSpecification.scala
src/test/scala/sigmastate/serialization/TwoArgumentSerializerSpecification.scala
src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala

Add String type and string literal syntax

---

build.sbt
src/main/scala/sigmastate/UnprovenTree.scala
src/main/scala/sigmastate/interpreter/Interpreter.scala
src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala

Initially, I've included "-Xfatal-warnings" but I could not fix deprecated `ECFieldElement.Fp` in a reasonable time here - http://github.com/ScorexFoundation/sigmastate-interpreter/blob/95cacbc00155b9488d74bc568661a559c5a402fd/src/main/scala/scapi/sigma/BcDlogFp.scala#L143

Sync scalac options with Ergo

---

docs/LangSpec.md
docs/wpaper/sigma.tex
src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/lang/SigmaBuilder.scala
src/main/scala/sigmastate/lang/SigmaPredef.scala
src/main/scala/sigmastate/lang/SigmaPrinter.scala
src/main/scala/sigmastate/lang/SigmaSpecializer.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/lang/Terms.scala
src/main/scala/sigmastate/types.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala
src/test/scala/sigmastate/utxo/AVLTreeScriptsSpecification.scala
src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
src/test/scala/sigmastate/utxo/ContextEnrichingSpecification.scala
src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
src/test/scala/sigmastate/utxo/SigmaCompilerSpecification.scala
src/test/scala/sigmastate/utxo/examples/AssetsAtomicExchangeSpecification.scala
src/test/scala/sigmastate/utxo/examples/AtomicSwapExampleSpecification.scala
src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
src/test/scala/sigmastate/utxo/examples/DemurrageExampleSpecification.scala
src/test/scala/sigmastate/utxo/examples/Rule110Specification.scala

fixes #235 
Changes:
- Global function `getVar[T](id: Byte): T` now returns `Option[T]`
- `Option.value` renamed `Option.get`
- `Option.valueOrElse` renamed `Option.getOrElse`
- all examples and wpaper updated

getVar to return Option[T]

---

docs/LangSpec.md
src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/lang/SigmaPredef.scala
src/main/scala/sigmastate/lang/exceptions/SigmaBinderExceptions.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala

Generic `deserialize` for constants

---

src/main/scala/org/ergoplatform/ErgoLikeContext.scala
src/main/scala/sigmastate/eval/Evaluation.scala
src/main/scala/sigmastate/interpreter/Context.scala
src/main/scala/sigmastate/interpreter/Interpreter.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/eval/CostingTest.scala
src/test/scala/sigmastate/eval/ErgoScriptTestkit.scala
src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala

New costing, etc.: Rewrite reduceToCrypto

---

build.sbt
lock.sbt
src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/interpreter/Interpreter.scala
src/main/scala/sigmastate/lang/SigmaBuilder.scala
src/main/scala/sigmastate/lang/SigmaPredef.scala
src/main/scala/sigmastate/lang/SigmaSpecializer.scala
src/main/scala/sigmastate/lang/Terms.scala
src/main/scala/sigmastate/lang/syntax/Exprs.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala
src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala

add ZKProof  function (zero-knowledge scope)

---

src/main/scala/org/ergoplatform/ErgoAddress.scala
src/main/scala/org/ergoplatform/ErgoBox.scala
src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
src/main/scala/sigmastate/UnprovenTree.scala
src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/eval/IRContext.scala
src/main/scala/sigmastate/interpreter/Interpreter.scala
src/main/scala/sigmastate/lang/SigmaCompiler.scala
src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
src/main/scala/sigmastate/utils/SigmaByteReader.scala
src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala
src/test/scala/sigmastate/eval/EvaluationTest.scala
src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
src/test/scala/sigmastate/utxo/SpamSpecification.scala
src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala

Use sigma-coster in ergo 

---

src/test/scala/sigmastate/lang/SigmaParserTest.scala

Add missing non-methods ops to the parser layer. Part 2.

---

sigma-impl/src/main/scala/sigma/util/Extensions.scala
src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/eval/CompiletimeCosting.scala
src/main/scala/sigmastate/eval/RuntimeCosting.scala
src/main/scala/sigmastate/lang/SigmaBinder.scala
src/main/scala/sigmastate/lang/SigmaBuilder.scala
src/main/scala/sigmastate/lang/SigmaCompiler.scala
src/main/scala/sigmastate/lang/SigmaParser.scala
src/main/scala/sigmastate/lang/SigmaSpecializer.scala
src/main/scala/sigmastate/lang/SigmaTyper.scala
src/main/scala/sigmastate/lang/SourceContext.scala
src/main/scala/sigmastate/lang/Terms.scala
src/main/scala/sigmastate/lang/Types.scala
src/main/scala/sigmastate/lang/exceptions/Exceptions.scala
src/main/scala/sigmastate/lang/exceptions/SigmaBinderExceptions.scala
src/main/scala/sigmastate/lang/exceptions/SigmaBuilderExceptions.scala
src/main/scala/sigmastate/lang/exceptions/SigmaInterpreterExceptions.scala
src/main/scala/sigmastate/lang/exceptions/SigmaSerializerExceptions.scala
src/main/scala/sigmastate/lang/exceptions/SigmaTyperExceptions.scala
src/main/scala/sigmastate/lang/syntax/Basic.scala
src/main/scala/sigmastate/lang/syntax/Core.scala
src/main/scala/sigmastate/lang/syntax/Exprs.scala
src/main/scala/sigmastate/lang/syntax/Literals.scala
src/test/scala/sigmastate/lang/LangTests.scala
src/test/scala/sigmastate/lang/SigmaBinderTest.scala
src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
src/test/scala/sigmastate/lang/SigmaParserTest.scala
src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
src/test/scala/sigmastate/lang/SigmaTyperTest.scala
src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala

Error-reporting in ErgoScript (compilation/runtime)

---

build.sbt
src/main/scala/org/ergoplatform/ErgoAddress.scala
src/main/scala/org/ergoplatform/ErgoScriptPredef.scala
src/main/scala/org/ergoplatform/settings/MonetarySettings.scala
src/main/scala/sigmastate/UnprovenTree.scala
src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/interpreter/Interpreter.scala
src/main/scala/sigmastate/lang/Terms.scala
src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
src/test/scala/org/ergoplatform/ErgoScriptPredefSpec.scala
src/test/scala/sigmastate/TestingInterpreterSpecification.scala
src/test/scala/sigmastate/crypto/SigningSpecification.scala
src/test/scala/sigmastate/eval/ErgoScriptTestkit.scala
src/test/scala/sigmastate/eval/EvaluationTest.scala
src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
src/test/scala/sigmastate/serialization/SubstConstantsSerializerSpecification.scala
src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
src/test/scala/sigmastate/utxo/BlockchainSimulationSpecification.scala
src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
src/test/scala/sigmastate/utxo/SpamSpecification.scala
src/test/scala/sigmastate/utxo/benchmarks/CrowdFundingKernelContract.scala
src/test/scala/sigmastate/utxo/examples/CoopExampleSpecification.scala
src/test/scala/sigmastate/utxo/examples/MixExampleSpecification.scala
src/test/scala/sigmastate/utxo/examples/RPSGameExampleSpecification.scala
src/test/scala/sigmastate/utxo/examples/ReversibleTxExampleSpecification.scala
src/test/scala/sigmastate/utxo/examples/XorGameExampleSpecification.scala

Close #454 
Todo:
ergo PR https://github.com/ergoplatform/ergo/pull/681

Add type check for deserialized script

---

build.sbt
src/main/scala/sigmastate/eval/CostingRules.scala
src/main/scala/sigmastate/eval/RuntimeCosting.scala

Switch to opCost with costedValue

---

src/main/scala/sigmastate/eval/RuntimeCosting.scala
src/main/scala/sigmastate/eval/TreeBuilding.scala
src/main/scala/sigmastate/types.scala
src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala

#416 
Since we don't serialize type substitutions in `MethodCallSerializer` we cannot support `getReg` with arbitrary expressions (with non-constant expressions it becomes `MethodCall`). Disabling `getReg` translation to `MethodCall` for now.

Limit Box.getReg to constant expressions only

---

src/main/scala/sigmastate/Values.scala
src/main/scala/sigmastate/lang/exceptions/SigmaSerializerExceptions.scala
src/main/scala/sigmastate/serialization/DataSerializer.scala
src/main/scala/sigmastate/serialization/SigmaSerializer.scala
src/main/scala/sigmastate/serialization/TypeSerializer.scala
src/main/scala/sigmastate/serialization/ValueSerializer.scala
src/main/scala/sigmastate/utils/SigmaByteReader.scala
src/test/scala/sigmastate/serialization/DeserializationResilience.scala
src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala
src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala

Check script tree depth limit during deserialization

---

build.sbt
src/main/scala/sigmastate/eval/Sized.scala

Comparison:
```
New:
2019-04-01 12:14:36 WARN  [ScalaTest-run] o.e.settings.ErgoSettings$ - NO CONFIGURATION FILE WAS PROVIDED. STARTING WITH DEFAULT SETTINGS FOR TESTNET!
2019-04-01 12:14:37 WARN  [ScalaTest-run] o.e.settings.ErgoSettings$ - NO CONFIGURATION FILE WAS PROVIDED. STARTING WITH DEFAULT SETTINGS FOR TESTNET!
2019-04-01 12:14:37 WARN  [ScalaTest-run] o.e.settings.ErgoSettings$ - NO CONFIGURATION FILE WAS PROVIDED. STARTING WITH DEFAULT SETTINGS FOR TESTNET!
2019-04-01 12:14:39 INFO  [pool-1-thread-2] s.c.u.NetworkTimeProvider - New offset adjusted: -29
Tx cost:1333370
Tx size: 38227
Input tokens: 0
Output tokens: 3
tx validation time: 1260
================================
Tx cost:1480305
Tx size: 36189
Input tokens: 9
Output tokens: 18
tx validation time: 706 …
```

Improve costing

---

sigmastate/src/main/scala/org/ergoplatform/ErgoAddress.scala

This PR contains:
* check that P2SH content bytes (192-bits hash of the corresponding script) are of proper length
* fixing examples for P2SH / P2S addresses in comments

Checking content length in P2SH, examples fixed

---

sigmastate/src/test/scala/sigmastate/serialization/AvlTreeSpecification.scala

This PR is introducing a new test for insert operation in AvlTreeSpecification only.

Test for insert operation in AvlTreeSpecification

---

sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala
sigmastate/src/main/scala/org/ergoplatform/validation/ValidationRules.scala
sigmastate/src/main/scala/sigmastate/Values.scala
sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
sigmastate/src/main/scala/sigmastate/interpreter/InterpreterContext.scala
sigmastate/src/test/scala/sigmastate/ScriptVersionSwitchSpecification.scala
sigmastate/src/test/scala/sigmastate/helpers/NegativeTesting.scala
sigmastate/src/test/scala/sigmastate/helpers/TestingHelpers.scala

Closes #637 
Introduces hard-forking features necessary for AOT -> JIT switch, as a result, this PR should be merged into 
develop only as part of v4.0-RC .
PR implements [validation checks](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/develop/docs/aot-jit-switch.md) performed by v4.0 release (see specification test cases).
The new checks are designed to support future v5.0 soft-fork.

Ensure v4.0 can support AOT -> JIT switch as v5.0 soft-fork (includes HF changes)

---

build.sbt
common/src/main/scala/scalan/AnyVals.scala
common/src/main/scala/scalan/util/BenchmarkUtil.scala
common/src/test/scala/scalan/TestUtils.scala
docs/LangSpec.md
docs/notes.md
library-api/src/main/scala/special/collection/Colls.scala
sigma-api/src/main/scala/special/sigma/SigmaDsl.scala
sigma-impl/src/main/scala/special/sigma/Mocks.scala
sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala
sigma-library/src/main/scala/special/sigma/SigmaDslUnit.scala
sigma-library/src/main/scala/special/sigma/impl/SigmaDslImpl.scala
sigmastate/src/main/scala/org/ergoplatform/ErgoBox.scala
sigmastate/src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala
sigmastate/src/main/scala/org/ergoplatform/ErgoLikeInterpreter.scala
sigmastate/src/main/scala/org/ergoplatform/SigmaConstants.scala
sigmastate/src/main/scala/org/ergoplatform/dsl/ContractSyntax.scala
sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
sigmastate/src/main/scala/sigmastate/eval/Evaluation.scala
sigmastate/src/main/scala/sigmastate/eval/RuntimeCosting.scala
sigmastate/src/main/scala/sigmastate/eval/TreeBuilding.scala
sigmastate/src/test/scala/special/sigma/ContractsTestkit.scala
sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
sigmastate/src/test/scala/special/sigma/SigmaDslStaginTests.scala

This PR contains refactoring and code improvements which can be merged into v4.0.
The changes are motivated by v5.0 work, but can be made in v4.0 and thus minimize v5.0 PR.
This is part 1, which contains:

Preparation refactoring towards v5.0 (part 2)

---

sigmastate/src/main/scala/sigmastate/interpreter/ErgoTreeEvaluator.scala
sigmastate/src/test/scala/sigmastate/TestsBase.scala
sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala

Old implementation is done in https://github.com/ScorexFoundation/sigmastate-interpreter/blob/e0905cc8c135fc4a6669f04636dd888aaa11572b/sigmastate/src/main/scala/sigmastate/eval/RuntimeCosting.scala#L1722 which is non-lazy.
The new v5.0 implementation is done in https://github.com/ScorexFoundation/sigmastate-interpreter/blob/68365862ac5548a644d91f9b062a38b1bebcfeef/sigmastate/src/main/scala/sigmastate/trees.scala#L1495-L1494 which is lazy for each branch and fixes the problem (See `property("Conditional access (data box register)")`).
In this PR:

Finalize v5.0: fix non-lazy If

---

core/src/main/scala/scalan/Base.scala
sigmastate/src/main/scala/sigmastate/eval/IRContext.scala
sigmastate/src/main/scala/sigmastate/interpreter/PrecompiledScriptProcessor.scala
sigmastate/src/main/scala/sigmastate/utils/Helpers.scala

Closes #778 
In this PR:
- mutable access to IR is protected by ReentrantLock
- improved assertion reporting

Fix possible race condition in PrecompiledScriptReducer 

---

common/src/main/scala/sigmastate/VersionContext.scala
common/src/main/scala/sigmastate/util.scala
common/src/test/scala/sigmastate/VersionTesting.scala
common/src/test/scala/sigmastate/VersionTestingProperty.scala
library-impl/src/main/scala/special/collection/CollsOverArrays.scala
library/src/test/scala/special/collections/CollsTests.scala
sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala
sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala
sigmastate/src/main/scala/sigmastate/Values.scala
sigmastate/src/main/scala/sigmastate/eval/CompiletimeCosting.scala
sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
sigmastate/src/main/scala/sigmastate/eval/Zero.scala
sigmastate/src/main/scala/sigmastate/lang/SigmaBuilder.scala
sigmastate/src/main/scala/sigmastate/serialization/DataSerializer.scala
sigmastate/src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
sigmastate/src/main/scala/sigmastate/serialization/ValueSerializer.scala
sigmastate/src/main/scala/sigmastate/trees.scala
sigmastate/src/main/scala/sigmastate/types.scala
sigmastate/src/main/scala/sigmastate/utxo/transformers.scala
sigmastate/src/test/scala/sigmastate/CrossVersionProps.scala
sigmastate/src/test/scala/sigmastate/ErgoTreeSpecification.scala
sigmastate/src/test/scala/sigmastate/ScriptVersionSwitchSpecification.scala
sigmastate/src/test/scala/sigmastate/TestsBase.scala
sigmastate/src/test/scala/sigmastate/eval/ErgoScriptTestkit.scala
sigmastate/src/test/scala/sigmastate/eval/EvaluationTest.scala
sigmastate/src/test/scala/sigmastate/lang/SigmaTyperTest.scala
sigmastate/src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
sigmastate/src/test/scala/special/sigma/ContractsTestkit.scala
sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala

In this PR:
- Closes #597 (see property("GroupElement.multiply equivalence"))
- #762 
- Publish a snapshot only if env.HAS_SECRETS == 'true'
- replace treeWithSegregation usages in tests with mkTestErgoTree
- tests for GroupElement.exp via MethodCall node
- test for Global.xor can be called via MethodCall node
- test for Coll.getOrElse,append,slice,exists,forall can be called via MethodCall node
- removing pattern cases for Coll.map, Coll.fold, Option.isDefined from CompiletimeCosting.scala (the logic is moved to the corresponding SMethod declaration)
- #780 
- #788

Finalize v5.0: resolve all TODO mainnet

---

sigmastate/src/main/scala/sigmastate/types.scala
sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala

Removed constraint on lambda of flatMap (any lambda will be supported in v5.0).

Finalize v5.0: fix flatMap (part 2)

---

sigmastate/src/main/scala/org/ergoplatform/ErgoLikeTransaction.scala

Since it contradicts the check for max box size in tx verification on the node - https://github.com/ergoplatform/ergo/blob/a4d1e62fb8f888a33db3fc5881c2090ec3dd0ebb/src/main/scala/org/ergoplatform/modifiers/mempool/ErgoTransaction.scala#L168

remove incorrect comment regarding max tokens limit in tx serialization;

---

package.json

This PR modifies package.json in order to allow individual modules exporting while ignores all `internal-*` files.
Modules can be imported as follows:
```js
import { Value, Values } from "sigmastate-js/core";
import { ErgoTrees } from "sigmastate-js/ergotree";
```
This is good because allows bundlers like webpack to "[tree-shake](https://developer.mozilla.org/en-US/docs/Glossary/Tree_shaking)" the code, when possible, and extract only what's needed for production.

Export modules individually

---

.gitignore
sigma-js/package.json

This PR moves `package.json` file to `sigma-js/` dir and makes use of `prepublishOnly` hook script (which will be automatically called on `npm publish`) to copy output files from `interpreter/js/target/scala-2.13/interpreter-fastopt/` to `sigma-js/dist/`. 
This also allows publishing npm package from inside the `sigma-js/` dir and having the corresponding `README.md` file in the published package.

Add new publish approach

---

build.sbt
sdk/shared/src/main/scala/org/ergoplatform/sdk/DataJsonEncoder.scala
sdk/shared/src/main/scala/org/ergoplatform/sdk/JsonCodecs.scala
sdk/shared/src/test/scala/org/ergoplatform/sdk/DataJsonEncoderSpecification.scala
sdk/shared/src/test/scala/org/ergoplatform/sdk/JsonSerializationSpec.scala

Ground work part 2 for #851 
Moved `DataJsonEncoder` and `JsonCodecs` to the `sdk` module. This is done because we need these to be available from the `sdk` module for EIP-5 implementation and we don't want the `sdk` module to depend on the `sc` module.

Move DataJsonEncoder and JsonCodecs to the sdk module

---

sigma-js/jest.config.js
sigma-js/package.json
sigma-js/tests/js/bindings.spec.js

In this PR:
* Fix pre-publish hook by updating relative path of `copy-output` script;
* Fix JS tests by restricting jest to only look at `sigma-js/node_modules` for module resolution; and
* Add `sigmastate-js` module mapper for JS output file.

Fix JS tests and publish script

---

sigma-js/README.md
sigma-js/package.json
sigma-js/sigmastate-js.d.ts

* Fix types exporting by tweaking `package.json` and adding export declarations in `d.ts` file.
* Add `ErgoTree.template()` and `ErgoTree.templateHex()` methods.
* Simplify NPM package installation instructions.

Tree template types

---

.github/workflows/ci.yml
build.sbt
interpreter/js/src/main/scala/sigmastate/crypto/Platform.scala
interpreter/js/src/main/scala/sigmastate/crypto/SigmaJsCryptoFacade.scala
sc/shared/src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala

Secure random for JS

---

interpreter/shared/src/main/scala/org/ergoplatform/ErgoAddress.scala
sc/shared/src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala

In this PR:
- Pay2SHAddress uses script id = 126 (instead of 1)

P2SH address to use 126 as scriptId

---

core/shared/src/main/scala/sigma/serialization/CoreByteReader.scala
data/shared/src/main/scala/sigma/ast/ErgoTree.scala
data/shared/src/main/scala/sigma/ast/methods.scala
data/shared/src/main/scala/sigma/ast/values.scala
data/shared/src/main/scala/sigma/serialization/CaseObjectSerialization.scala
data/shared/src/main/scala/sigma/serialization/ErgoTreeSerializer.scala
data/shared/src/main/scala/sigma/serialization/MethodCallSerializer.scala
sc/shared/src/test/scala/sigmastate/ErgoTreeSpecification.scala
sc/shared/src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala

Fixes https://github.com/ScorexFoundation/sigmastate-interpreter/issues/928
Add a flag `isUsingBlockchainContext` to ErgoTree similar to the existing `hasDeserialize`.

Add flag `isUsingBlockchainContext` to ErgoTree

---

data/shared/src/main/scala/sigma/ast/CostItem.scala
sc/shared/src/main/scala/scalan/primitives/Functions.scala
sc/shared/src/main/scala/scalan/primitives/Thunks.scala
sc/shared/src/main/scala/scalan/staged/Transforming.scala
sc/shared/src/main/scala/special/collection/CollsUnit.scala
sc/shared/src/main/scala/special/sigma/impl/SigmaDslImpl.scala
sdk/shared/src/main/scala/org/ergoplatform/sdk/Extensions.scala
sdk/shared/src/test/scala/org/ergoplatform/sdk/ExtensionsSpec.scala

In this PR:
* unused arguments in `mirrorNode` / `mirrorVar` / `mirrorSymbols` removed 
* unused `GenIterableOps` removed
* unused `class DoubleOps`
* `Coll.mapReduce` test fixed (it actually tested `GenIterableOps.mapReduce`)

Removing unused code #3

---

core/shared/src/main/scala/sigma/VersionContext.scala
data/shared/src/main/scala/org/ergoplatform/ErgoAddress.scala
sc/shared/src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala

In this PR:
- added property("Pay2SHAddress.script should create ErgoTree v0")
- added property("using default VersionContext still creates ErgoTree v0")
- Rollback changes in Pay2SHAddress behaviour introduced in v5.0.14-RC

More tests related to ErgoTree versioning

---

data/shared/src/main/scala/sigma/ast/SigmaPredef.scala
docs/LangSpec.md
parsers/shared/src/test/scala/sigmastate/lang/SigmaParserTest.scala
sc/shared/src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
sc/shared/src/test/scala/sigmastate/lang/SigmaTyperTest.scala

This PR contains new ErgoScript predefined function to construct big integer from string.
```
/** Transforms Base16 encoded string literal into constant of type Coll[Byte].
* It is a compile-time operation and only string literal (constant) can be its
* argument.
*/
def bigInt(input: String): BigInt
```
example: ` bigInt("326674862673836209462483453386286740270338859283019276168539876024851191344")`

bigInt predefined function

---

sdk/js/src/main/scala/org/ergoplatform/sdk/js/ContractTemplate.scala
sdk/shared/src/main/scala/org/ergoplatform/sdk/ContractTemplate.scala

Parse ContractTemplate from JSON string

---

core/shared/src/main/scala/sigma/serialization/CoreDataSerializer.scala
core/shared/src/main/scala/sigma/util/Extensions.scala
interpreter/shared/src/test/scala/sigma/serialization/DataSerializerSpecification.scala
sc/shared/src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala

This PR introduces a new check during BigInt serialization in CoreDataSerializer.
This prevents oversized BigInt to be put into registers or ErgoTree constants and hence create unparsable boxes, which will be rejected by the blockchain.
closes #991

Check BigInt size on serialization

---

parsers/shared/src/test/scala/sigmastate/helpers/SigmaPPrint.scala
parsers/shared/src/test/scala/sigmastate/lang/LangTests.scala
parsers/shared/src/test/scala/sigmastate/lang/SigmaParserTest.scala
sc/jvm/src/test/scala/sigmastate/helpers/SigmaPPrintSpec.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationBase.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV5.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV6.scala
sc/shared/src/test/scala/sigma/SigmaDslTesting.scala
sc/shared/src/test/scala/sigmastate/CompilerCrossVersionProps.scala
sc/shared/src/test/scala/sigmastate/lang/SigmaBinderTest.scala
sc/shared/src/test/scala/sigmastate/lang/SigmaTyperTest.scala

In this PR: 
- SigmaDslSpecification is refactored to LanguageSpecificationV5 and V6.
- Feature.isSupportedBy(versionContext) method implemented to allow correct testing of `newFeature` test cases
- All `newFeature` tests moved to LanguageSpecificationV6

[6.0] Improved and correct testing of  `newFeature` test cases

---

core/jvm/src/main/scala/sigma/reflection/Platform.scala
core/shared/src/main/scala/sigma/reflection/ReflectionData.scala
core/shared/src/main/scala/sigma/reflection/StaticImpl.scala
core/shared/src/main/scala/sigma/reflection/package.scala
data/shared/src/main/scala/sigma/SigmaDataReflection.scala
sc/shared/src/test/scala/sigma/SigmaDslSpecification.scala
sc/shared/src/test/scala/sigmastate/helpers/CompilerTestingCommons.scala

In this PR:
- missing classes registered 
- Scala objects that are used reflectively (in Kiama rewriting) declared with MODULE$ field
- additional sanity check added in isDebug mode in SigmaDslSpecification

[sigma-js] Add missing reflection metadata

---

core/shared/src/main/scala/sigma/ast/SType.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV6.scala
sc/shared/src/test/scala/sigmastate/TestingInterpreterSpecification.scala
sc/shared/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala

Close #877
It has test from the issue as well similar ones for all the Numeric types.
Also, Downcast from BigInt to BigInt and Upcast from BigInt to BigInt are fixed now

[6.0] Fix for downcasting BigInt to Long fails

---

core/shared/src/main/scala/sigma/VersionContext.scala
interpreter/shared/src/main/scala/sigmastate/interpreter/Interpreter.scala
sc/shared/src/test/scala/sigma/SigmaDslSpecification.scala
sc/shared/src/test/scala/sigma/SigmaDslTesting.scala
sc/shared/src/test/scala/sigmastate/ScriptVersionSwitchSpecification.scala

For #846 
I've accumulated the deserialization cost into the total cost and updated all the relevant test cases with costs for all ErgoTree versions when V3 is activated.

[v6.0] Accumulate ErgoTree deserialization cost

---

data/shared/src/main/scala/sigma/ast/SMethod.scala
data/shared/src/main/scala/sigma/serialization/MethodCallSerializer.scala
sc/shared/src/main/scala/sigma/compiler/phases/SigmaTyper.scala

This PR contains new features in SMethod and MethodCallSerialize, extracted from #979, #984, #989
* SMethod - new arguments, `explicitTypeArgs` and `userDefinedInvoke`
* MethodCallSerializer - support for polymorphic calls serialization

[6.0]  Common SMethod and MethodCallSerializer new features

---

core/shared/src/main/scala/sigma/ast/SType.scala
core/shared/src/main/scala/sigma/ast/STypeParam.scala
core/shared/src/main/scala/sigma/ast/TypeCodes.scala
core/shared/src/main/scala/sigma/serialization/TypeSerializer.scala
interpreter/shared/src/test/scala/sigma/serialization/MethodCallSerializerSpecification.scala
interpreter/shared/src/test/scala/sigma/serialization/generators/ObjectGenerators.scala
parsers/shared/src/test/scala/sigmastate/helpers/SigmaPPrint.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV5.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV6.scala
sc/shared/src/test/scala/sigma/SigmaDslTesting.scala
sc/shared/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala

This PR is adding higher-order lambdas support in serialization, thus making them useful.
Example:
```
{
val c = Coll(Coll(1))
def fn(xs: Coll[Int]) = {
val inc = { (x: Int) => x + 1 }
def apply(in: (Int => Int, Int)) = in._1(in._2)
val ys = xs.map { (x: Int) => apply((inc, x)) }
ys.size == xs.size && ys != xs
}
c.exists(fn)
}
```
Close #847

[6.0] Serialize SFunc in TypeSerializer

---

core/shared/src/main/scala/sigma/SigmaDsl.scala
core/shared/src/main/scala/sigma/reflection/ReflectionData.scala
core/shared/src/main/scala/sigma/serialization/CoreDataSerializer.scala
data/shared/src/main/scala/sigma/SigmaDataReflection.scala
data/shared/src/main/scala/sigma/ast/SigmaPredef.scala
data/shared/src/main/scala/sigma/ast/methods.scala
data/shared/src/main/scala/sigma/data/CHeader.scala
data/shared/src/main/scala/sigma/data/CSigmaDslBuilder.scala
docs/LangSpec.md
interpreter/shared/src/main/scala/sigmastate/interpreter/Interpreter.scala
interpreter/shared/src/test/scala/sigma/serialization/MethodCallSerializerSpecification.scala
interpreter/shared/src/test/scala/special/sigma/SigmaTestingData.scala
sc/shared/src/main/scala/sigma/compiler/ir/Base.scala
sc/shared/src/main/scala/sigma/compiler/ir/GraphBuilding.scala
sc/shared/src/main/scala/sigma/compiler/ir/GraphIRReflection.scala
sc/shared/src/main/scala/sigma/compiler/ir/TreeBuilding.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/SigmaDslUnit.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/impl/SigmaDslImpl.scala
sc/shared/src/main/scala/sigma/compiler/phases/SigmaTyper.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV6.scala
sc/shared/src/test/scala/sigmastate/ErgoTreeSpecification.scala
sc/shared/src/test/scala/sigmastate/TestingInterpreterSpecification.scala
sc/shared/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
sc/shared/src/test/scala/sigmastate/utxo/examples/ExecuteFromExamplesSpecification.scala

This PR is introducing  new Global.deserializeRaw method which is allowing to deserialize a typed object from underlying bytes. It is compatible (has roundtrip with) Global.serialize from #989 .
example:
```
{
val src = getVar[Coll[Short]](21).get
val ba = serialize(src)
val restored = deserializeTo[Coll[Short]](ba)
src == restored
}
```

[6.0] Global.deserializeTo[] method

---

core/shared/src/main/scala/sigma/SigmaDsl.scala
core/shared/src/main/scala/sigma/reflection/ReflectionData.scala
data/shared/src/main/scala/sigma/SigmaDataReflection.scala
data/shared/src/main/scala/sigma/ast/CostKind.scala
data/shared/src/main/scala/sigma/ast/SMethod.scala
data/shared/src/main/scala/sigma/ast/methods.scala
data/shared/src/main/scala/sigma/ast/trees.scala
data/shared/src/main/scala/sigma/data/CSigmaDslBuilder.scala
data/shared/src/main/scala/sigma/pow/Autolykos2PowValidation.scala
interpreter/shared/src/test/scala/sigma/serialization/MethodCallSerializerSpecification.scala
interpreter/shared/src/test/scala/sigmastate/eval/BasicOpsTests.scala
sc/shared/src/main/scala/sigma/compiler/ir/GraphBuilding.scala
sc/shared/src/main/scala/sigma/compiler/ir/GraphIRReflection.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/SigmaDslUnit.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/impl/SigmaDslImpl.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV6.scala
sc/shared/src/test/scala/sigmastate/ErgoTreeSpecification.scala
sc/shared/src/test/scala/sigmastate/TestingInterpreterSpecification.scala

In this PR, Global.powHit() method implemented, to check PoW for custom variant of Autolykos2 hash function

[6.0.0] Autolykos 2 validation for custom message

---

build.sbt
data/shared/src/main/scala/sigma/ast/SigmaPredef.scala
interpreter/shared/src/main/scala/sigmastate/interpreter/Interpreter.scala
profile-sbt.sh
sc/shared/src/main/scala/sigma/compiler/ir/Base.scala
sc/shared/src/main/scala/sigma/compiler/ir/GraphBuilding.scala
sc/shared/src/main/scala/sigma/compiler/ir/TreeBuilding.scala
sc/shared/src/main/scala/sigma/compiler/phases/SigmaTyper.scala
sc/shared/src/test/scala/sigma/SigmaDslTesting.scala
sc/shared/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
sc/shared/src/test/scala/sigmastate/utxo/examples/ExecuteFromExamplesSpecification.scala

* scrypto version updated to 3.0.0 (close #1030 )
* #976

Candidate for 5.0.15 release

---

core/shared/src/main/scala/sigma/data/CGroupElement.scala
core/shared/src/main/scala/sigma/reflection/ReflectionData.scala
data/shared/src/main/scala/sigma/SigmaDataReflection.scala
data/shared/src/main/scala/sigma/ast/methods.scala
docs/LangSpec.md
sc/shared/src/main/scala/sigma/compiler/ir/GraphBuilding.scala
sc/shared/src/main/scala/sigma/compiler/ir/GraphIRReflection.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/CollsUnit.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/impl/CollsImpl.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV6.scala
sc/shared/src/test/scala/sigmastate/ErgoTreeSpecification.scala
sc/shared/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala

In this PR, coll.distinct method, earlier introduced in 6.0.0 candidate, has been removed, as it may be used for DoS attacks, see #1051 for details. Another alternative was to use type-based recursive cost evaluation like done in DataSerializer, but removing is simpler, and in case of need distinct check can be done in ErgoScript for small collections. 
Close #1051

Coll.distinct method removed

---

core/shared/src/main/scala/sigma/SigmaDsl.scala
data/shared/src/main/scala/sigma/ast/methods.scala
data/shared/src/main/scala/sigma/data/CSigmaDslBuilder.scala
docs/LangSpec.md
interpreter/shared/src/test/scala/sigmastate/eval/BasicOpsTests.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/SigmaDslUnit.scala
sc/shared/src/main/scala/sigma/compiler/ir/wrappers/sigma/impl/SigmaDslImpl.scala
sc/shared/src/test/scala/sigma/LanguageSpecificationV6.scala
sc/shared/src/test/scala/sigmastate/TestingInterpreterSpecification.scala

In this PR, Global.powHit result type set to UnsignedBigInt

UnsignedBigInt result type for Global.powHit
