ergoplatform/sigmastate-interpreter

- docs/wpaper/sigma.tex
- src/main/scala/scapi/sigma/dlog/Dealer.scala
Questions:
- do we need structure types e.g. `struct { a: Int; b: Boolean } ?
- do we need subtyping?
- do we assume all items in a collection have the same type?
> Definition of type families for expressions and sigma statements

- src/main/scala/sigmastate/serialization/OrSerializer.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/trees.scala
- src/test/scala/sigmastate/serialization/OrSerializerSpecification.scala
> Add OrSerializer

- src/main/scala/sigmastate/serialization/ByteArrayConstantSerializer.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/values.scala
- src/test/scala/sigmastate/serialization/ByteArrayConstantSerializerSpecification.scala
- src/test/scala/sigmastate/serialization/SerializationSpecification.scala
- src/test/scala/sigmastate/serialization/generators/ConcreteCollectionGenerators.scala
- src/test/scala/sigmastate/serialization/generators/ValueGeneratots.scala
> Add ByteArrayConstant serializer

- src/test/java/gf2t/GF2_128Bench.java
- src/test/java/gf2t/GF2_128Test.java
- src/test/java/gf2t/ReadableTest.java
> Rework tests for GF2_128. Also test cases now have human readable names.

- docs/LangSpec.md
- src/main/scala/sigmastate/lang/SigmaPredef.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/trees.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/utxo/BlockchainSimulationSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoInterpreterSpecification.scala
Resolves #50. 
Also sha256 function added.
> Not removed and example rewritten

- src/test/scala/sigmastate/utxo/ErgoInterpreterSpecification.scala
> Add failing cases for brother and register specs.

- src/main/scala/scapi/sigma/DLogProtocol.scala
- src/main/scala/sigmastate/interpreter/Interpreter.scala
- src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/utxo/ErgoInterpreter.scala
- src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoInterpreterSpecification.scala
- avoid composition of PartialFunctions
- pull rules out of loops to avoid closure allocations
- reduce allocations
> Refactoring of reduceToCrypto + performance optimizations

- src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
> WIP: Add more collection examples to `CollectionOperationsSpecification`

- docs/LangSpec.md
- src/main/scala/sigmastate/interpreter/Interpreter.scala
- src/main/scala/sigmastate/lang/SigmaBinder.scala
- src/main/scala/sigmastate/lang/SigmaPredef.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/lang/SigmaTyper.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utils/Helpers.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- src/test/scala/sigmastate/lang/SigmaBinderTest.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/serialization/TwoArgumentSerializerSpecification.scala
- src/test/scala/sigmastate/utxo/AVLTreeScriptsSpecification.scala
- src/test/scala/sigmastate/utxo/ArithmeticOperationsSpecification.scala
- src/test/scala/sigmastate/utxo/ContextEnrichingSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/SigmaCompilerSpecification.scala
- src/test/scala/sigmastate/utxo/examples/AtomicSwapExampleSpecification.scala
- src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala
> Generalize ContextVariables

- src/main/scala/sigmastate/lang/SigmaTyper.scala
- src/main/scala/sigmastate/serialization/transformers/ByIndexSerializer.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
> READY: Make ByIndex.index type of SInt

- docs/TypeSerialization.md
- src/main/scala/sigmastate/Values.scala
- src/main/scala/sigmastate/serialization/CollectionConstantSerializer.scala
- src/main/scala/sigmastate/serialization/STypeSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/ExtractRegisterAsSerializer.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/types.scala
- src/test/scala/sigmastate/serialization/AndSerializerSpecification.scala
- src/test/scala/sigmastate/serialization/OrSerializerSpecification.scala
Please see TypeSerialization.md
> Spec for new optimised encoding of SType values  

- src/main/scala/org/ergoplatform/ErgoBox.scala
- src/main/scala/sigmastate/serialization/DataSerializer.scala
> Renamed boxId to index in ErgoBox

- src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- src/main/scala/sigmastate/interpreter/Context.scala
- src/main/scala/sigmastate/serialization/ConcreteCollectionSerializer.scala
- src/main/scala/sigmastate/serialization/ConstantSerializer.scala
- src/main/scala/sigmastate/serialization/ProveDlogSerializer.scala
- src/main/scala/sigmastate/serialization/SelectFieldSerializer.scala
- src/main/scala/sigmastate/serialization/TaggedVariableSerializer.scala
- src/main/scala/sigmastate/serialization/TupleSerializer.scala
- src/main/scala/sigmastate/serialization/TwoArgumentsSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/AppendSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/BooleanTransformerSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/ByIndexSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/DeserializeContextSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/DeserializeRegisterSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/ExtractRegisterAsSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/FoldSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/LogicalTransformerSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/MapCollectionSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/ProveDiffieHellmanTupleSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/SimpleTransformerSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/SliceSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/UpcastSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/WhereSerializer.scala
- src/main/scala/sigmastate/serialization/trees/QuadrupleSerializer.scala
- src/main/scala/sigmastate/serialization/trees/Relation2Serializer.scala
- src/main/scala/sigmastate/serialization/trees/Relation3Serializer.scala
- src/main/scala/sigmastate/utils/ByteReader.scala
- src/main/scala/sigmastate/utils/ByteWriter.scala
- src/main/scala/sigmastate/utils/Extensions.scala
- src/test/scala/sigmastate/serialization/TypeSerializerSpecification.scala
> Decouple ByteReader/ByteWriter API from Sigma (via extension)

- src/main/scala/sigmastate/AvlTreeData.scala
- src/main/scala/sigmastate/serialization/DataSerializer.scala
- src/main/scala/sigmastate/serialization/GroupElementSerializer.scala
> Extract serializers for SGroupElement and SAvlTree from DataSerializer

- src/main/scala/sigmastate/serialization/DataSerializer.scala
- src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala
> Optimize byte array (de)serialization in `DataSerializer` (whole array at once)

- src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- src/main/scala/org/ergoplatform/ErgoLikeTransaction.scala
- src/main/scala/sigmastate/AvlTreeData.scala
- src/main/scala/sigmastate/interpreter/Context.scala
- src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
- src/main/scala/sigmastate/serialization/ConcreteCollectionBooleanConstantSerializer.scala
- src/main/scala/sigmastate/serialization/ConcreteCollectionSerializer.scala
- src/main/scala/sigmastate/serialization/DataSerializer.scala
- src/main/scala/sigmastate/serialization/TupleSerializer.scala
- src/main/scala/sigmastate/serialization/TypeSerializer.scala
- src/main/scala/sigmastate/utils/ByteWriter.scala
- src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala
- src/test/scala/sigmastate/utils/ByteReaderWriterImpSpecification.scala
> Add ByteWriter.putUByte(Int) and relax input types for putUShort and putUInt;

- src/main/scala/sigmastate/serialization/transformers/ProveDiffieHellmanTupleSerializer.scala
> Save two byte on serialization for const parameters in PDHT

- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/transformers/FoldSerializer.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/serialization/TransformersSerializationSpec.scala
- src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
- src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
> Generalize Fold[A] to Fold[A,B] (accumulator type);

- src/main/scala/scapi/sigma/DLogProtocol.scala
- src/main/scala/scapi/sigma/SigmaProtocolFunctions.scala
Reason: ["interactive protocols code has been abandoned for long time"](
https://github.com/ScorexFoundation/sigmastate-interpreter/issues/192#issuecomment-408357571)
Close #192
> Remove ActorParty (ActorProver, ActorVerifier, DLogActorProver, DLogActorVerifier)

- src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- src/main/scala/org/ergoplatform/ErgoLikeTransaction.scala
- src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala
> Add an array of Digest32 values in ErgoLikeTransaction

- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaParser.scala
- src/main/scala/sigmastate/lang/SigmaPredef.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/OpCodes.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/trees.scala
- src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/serialization/TransformersSerializationSpec.scala
- src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
> add fromBase64, fromBase58, etc decoding function

- src/main/scala/org/ergoplatform/ErgoAddress.scala
- src/main/scala/org/ergoplatform/ErgoLikeContext.scala
- src/main/scala/org/ergoplatform/ErgoLikeInterpreter.scala
- src/main/scala/org/ergoplatform/ErgoTransactionValidator.scala
- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaPredef.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/OpCodes.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/serialization/TransformersSerializationSpec.scala
- src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
- src/test/scala/sigmastate/utxo/BlockchainSimulationSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/SpamSpecification.scala
- src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
- src/test/scala/sigmastate/utxo/examples/Rule110Specification.scala
> add PK: String -> Value[SigmaProp] decoding of public keys

- src/main/scala/org/ergoplatform/ErgoAddress.scala
- src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala
> Fix recursive `Pay2SHAddress.apply()` call and pull spec from ergo

- src/main/scala/org/ergoplatform/ErgoAddress.scala
- src/main/scala/org/ergoplatform/ErgoLikeContext.scala
- src/main/scala/org/ergoplatform/ErgoTransactionValidator.scala
- src/main/scala/sigmastate/eval/CompiletimeCosting.scala
- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaCompiler.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/OpCodes.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala
- src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
- src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/serialization/TransformersSerializationSpec.scala
- src/test/scala/sigmastate/utxo/BlockchainSimulationSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/SpamSpecification.scala
- src/test/scala/sigmastate/utxo/benchmarks/CrowdFundingScriptContract.scala
- src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
- src/test/scala/sigmastate/utxo/examples/Rule110Specification.scala
> Remove ErgoAddressToSigmaProp from ErgoTree, remove ErgoLikeInterpreterContext.Metadata

- docs/LangSpec.md
- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/OpCodes.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/serialization/TransformersSerializationSpec.scala
- src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
> Add new field Box.creationInfo

- src/main/scala/sigmastate/lang/SigmaParser.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
> Implement "-" prefix unary op for constants 

- src/main/scala/scapi/sigma/BcDlogFp.scala
- src/main/scala/scapi/sigma/DLogProtocol.scala
- src/main/scala/scapi/sigma/DiffieHellmanTupleProtocol.scala
- src/main/scala/scapi/sigma/DlogGroup.scala
- src/main/scala/scapi/sigma/SigmaProtocolFunctions.scala
- src/main/scala/sigmastate/interpreter/Interpreter.scala
- src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
Close #175 . Duplicate SecureRandom instantiations eliminated, Random.randomBytes replaced with secureRandom usage.
>  Improve randomness generation

- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/OpCodes.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/FilterSerializer.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/serialization/TransformersSerializationSpec.scala
- src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
> Rename collection operation `where` to `filter`

- src/main/scala/sigmastate/Values.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/eval/TreeBuilding.scala
- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/transformers/BooleanTransformerSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/FoldSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/MapCollectionSerializer.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/eval/CompilerItTest.scala
- src/test/scala/sigmastate/eval/ErgoTreeBuildingTest.scala
- src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/SpamSpecification.scala
- src/test/scala/sigmastate/utxo/examples/CrowdfundingExampleSpecification.scala
- src/test/scala/sigmastate/utxo/examples/Rule110Specification.scala
> MapCollection, Fold, Exists, ForAll refactor (from TaggedVar to Lambda/FuncValue)

- src/main/scala/org/ergoplatform/ErgoBox.scala
- src/main/scala/org/ergoplatform/ErgoLikeTransaction.scala
- src/main/scala/sigmastate/serialization/BlockValueSerializer.scala
- src/main/scala/sigmastate/serialization/ConcreteCollectionSerializer.scala
- src/main/scala/sigmastate/serialization/DataSerializer.scala
- src/main/scala/sigmastate/serialization/SigmaSerializer.scala
- src/main/scala/sigmastate/serialization/TupleSerializer.scala
- src/main/scala/sigmastate/serialization/ValDefSerializer.scala
- src/main/scala/sigmastate/serialization/transformers/SigmaTransformerSerializer.scala
- src/main/scala/sigmastate/utils/SigmaByteReader.scala
- src/main/scala/sigmastate/utils/SigmaByteWriter.scala
- src/test/scala/sigmastate/utxo/SerializationRoundTripSpec.scala
> Add (de)serializer with generic Reader/Writer API

- lock.sbt
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala
> Check max size of big int in ByteArrayToBigInt

- src/main/scala/org/ergoplatform/ErgoLikeContext.scala
- src/main/scala/sigmastate/eval/CostingDataContext.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/eval/TreeBuilding.scala
- src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/ContextEnrichingSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
> Make CostingBox a thin wrapper over ErgoBox

- src/main/scala/sigmastate/eval/CompiletimeCosting.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/serialization/ModQArithOpSerializer.scala
- src/main/scala/sigmastate/serialization/ModQSerializer.scala
- src/main/scala/sigmastate/serialization/OpCodes.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/sigmastate.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/types.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/serialization/ModQSerializerSpecification.scala
- src/test/scala/sigmastate/utxo/SigmaCompilerSpecification.scala
> Add modular arithmetic operators

- build.sbt
- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaParser.scala
- src/main/scala/sigmastate/serialization/OpCodes.scala
- src/main/scala/sigmastate/sigmastate.scala
- src/main/scala/sigmastate/trees.scala
- src/test/scala/sigmastate/lang/SigmaBinderTest.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/utxo/ContextEnrichingSpecification.scala
> Parser layer for missing operations (#324)

- build.sbt
- lock.sbt
- src/main/scala/sigmastate/eval/Evaluation.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
- src/main/scala/sigmastate/serialization/SubstConstantsSerializer.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/test/scala/sigmastate/eval/ErgoScriptTestkit.scala
- src/test/scala/sigmastate/eval/EvaluationTest.scala
- src/test/scala/sigmastate/serialization/SubstConstantsSerializerSpecification.scala
> SubstConst evaluation + (de)serialization

- build.sbt
- lock.sbt
- src/main/scala/org/ergoplatform/ErgoLikeContext.scala
- src/main/scala/sigmastate/eval/CostingDataContext.scala
- src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- src/test/scala/sigmastate/eval/CompilerItTest.scala
- src/test/scala/sigmastate/eval/CostingTest.scala
- src/test/scala/sigmastate/eval/ErgoScriptTestkit.scala
- src/test/scala/sigmastate/eval/ErgoTreeBuildingTest.scala
- src/test/scala/sigmastate/eval/ExampleContracts.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- src/test/scala/sigmastate/utxo/ComplexSigSpecification.scala
- src/test/scala/sigmastate/utxo/benchmarks/CrowdFundingContract.scala
- src/test/scala/sigmastate/utxo/benchmarks/CrowdFundingKernelContract.scala
- src/test/scala/sigmastate/utxo/benchmarks/CrowdFundingScriptContract.scala
- src/test/scala/sigmastate/utxo/benchmarks/CrowdfundingBenchmark.scala
- src/test/scala/sigmastate/utxo/examples/AssetsAtomicExchangeSpecification.scala
- src/test/scala/sigmastate/utxo/examples/AtomicSwapExampleSpecification.scala
- src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
- src/test/scala/sigmastate/utxo/examples/CoopExampleSpecification.scala
- src/test/scala/sigmastate/utxo/examples/CrowdfundingExampleSpecification.scala
- src/test/scala/sigmastate/utxo/examples/DemurrageExampleSpecification.scala
- src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala
> Switch HEIGHT type to Int

- docs/LANG.md
- docs/LangSpec.md
- src/main/scala/org/ergoplatform/ErgoScriptPredef.scala
- src/main/scala/sigmastate/basics/DLogProtocol.scala
- src/main/scala/sigmastate/basics/DiffieHellmanTupleProtocol.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/utxo/transformers.scala
See `@since 1.9` and `@since 2.0` annotation
> SigmaPredef functions for 1.9 and 2.0 described in LangSpec.md

- docs/LANG.md
- docs/LangSpec.md
- src/main/scala/sigmastate/types.scala
Please search for `@since 1.9`, `@since 2.0`, `@since Mainnet`.
This denote the milestone for the method to appear first.
> Updated methods specifiaction in LangSpec.md

- build.sbt
- lock.sbt
- src/main/scala/sigmastate/Values.scala
- src/main/scala/sigmastate/eval/DataCosting.scala
- src/main/scala/sigmastate/eval/Evaluation.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/eval/TreeBuilding.scala
- src/main/scala/sigmastate/types.scala
- src/test/scala/sigmastate/eval/CostingTest.scala
- src/test/scala/sigmastate/eval/ExampleContracts.scala
- src/test/scala/sigmastate/utxo/examples/AssetsAtomicExchangeSpecification.scala
Most of the changes are in Special and Sigma.
> Optimizations of graph transformations

- docs/sigmastate_protocols/compile.sh
- docs/sigmastate_protocols/sigmastate_protocols.bib
- docs/sigmastate_protocols/sigmastate_protocols.tex
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/examples/ReversibleTxExampleSpecification.scala
- src/test/scala/sigmastate/utxo/examples/XorGameExampleSpecification.scala
Added XOR game example (complete) and documentation (in progress)
> Protocol examples (XOR game)

- src/main/scala/sigmastate/lang/Types.scala
- src/main/scala/sigmastate/lang/syntax/Core.scala
- src/main/scala/sigmastate/lang/syntax/Exprs.scala
- src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- src/test/scala/sigmastate/eval/CostingTest.scala
- src/test/scala/sigmastate/eval/ErgoTreeBuildingTest.scala
- src/test/scala/sigmastate/eval/EvaluationTest.scala
- src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
> Add `def` function declaration

- src/main/scala/sigmastate/eval/CompiletimeCosting.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/eval/TreeBuilding.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
> Recognize non-const ProveDlog and ProveDHTuple

- build.sbt
- docs/LangSpec.md
- docs/TypeSerialization.md
- lock.sbt
- src/main/scala/org/ergoplatform/ErgoBox.scala
- src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- src/main/scala/sigmastate/eval/Evaluation.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/lang/Types.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/test/scala/org/ergoplatform/ErgoScriptPredefSpec.scala
- src/test/scala/sigmastate/eval/CompilerItTest.scala
- src/test/scala/sigmastate/eval/CostingTest.scala
- src/test/scala/sigmastate/eval/ErgoScriptTestkit.scala
- src/test/scala/sigmastate/eval/EvaluationTest.scala
- src/test/scala/sigmastate/eval/MeasureIRContext.scala
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
- src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
- src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala
> Correct costing of Thunks + fix of Thunk schedule

- docs/soft-fork-log.md
- src/main/scala/sigmastate/eval/CostingRules.scala
- src/main/scala/sigmastate/eval/Evaluation.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/eval/TreeBuilding.scala
- src/main/scala/sigmastate/lang/SigmaBuilder.scala
- src/main/scala/sigmastate/lang/SigmaSpecializer.scala
- src/main/scala/sigmastate/serialization/transformers/FilterSerializer.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/main/scala/sigmastate/utxo/transformers.scala
- src/test/scala/sigmastate/CostingSpecification.scala
- src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
- src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
- src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
- src/test/scala/special/sigma/SigmaDslTest.scala
> Finish Coll.filter implementation

- src/main/scala/sigmastate/eval/CostingRules.scala
- src/main/scala/sigmastate/eval/Evaluation.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/test/scala/sigmastate/CostingSpecification.scala
- src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- src/test/scala/special/sigma/SigmaDslTest.scala
> SOption.map and filter implementation

- build.sbt
All the required code is merged to ergo v2.1, new-sigma is not updated anymore
> Change ergo task to v2.1

- src/main/scala/sigmastate/eval/CompiletimeCosting.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/eval/TreeBuilding.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/test/scala/sigmastate/utxo/SigmaCompilerSpecification.scala
> Fix plusModQ, minusModQ costing

- src/test/scala/sigmastate/utxo/examples/ReversibleTxExampleSpecification.scala
> Switch to a fold variant with function in ReversibleTxExampleSpec

- sigma-api/src/main/scala/special/sigma/SigmaDsl.scala
- sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala
- src/main/scala/sigmastate/lang/SigmaTyper.scala
- src/main/scala/sigmastate/types.scala
- src/test/scala/sigmastate/CostingSpecification.scala
- src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
- src/test/scala/sigmastate/lang/SigmaParserTest.scala
- src/test/scala/sigmastate/utxo/ContextEnrichingSpecification.scala
- src/test/scala/special/sigma/SigmaDslTest.scala
> add `xor` predefined operation (byte-wise)

- src/main/scala/sigmastate/eval/CostingRules.scala
- src/main/scala/sigmastate/eval/Evaluation.scala
- src/main/scala/sigmastate/utxo/CostTable.scala
- src/test/scala/sigmastate/CostingSpecification.scala
- src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
- src/test/scala/special/sigma/SigmaDslTest.scala
> Finish Coll.flatMap implementation

- src/main/scala/sigmastate/eval/TreeBuilding.scala
- src/test/scala/sigmastate/CostingSpecification.scala
- src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
- src/test/scala/special/sigma/SigmaDslTest.scala
> Fix Coll.zip costing

- src/main/scala/org/ergoplatform/ErgoBox.scala
- src/main/scala/org/ergoplatform/ErgoConstants.scala
- src/main/scala/org/ergoplatform/ErgoLikeContext.scala
- src/main/scala/sigmastate/interpreter/Interpreter.scala
- src/main/scala/sigmastate/serialization/SigmaSerializer.scala
- src/main/scala/sigmastate/trees.scala
- src/main/scala/sigmastate/types.scala
- src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
- src/test/scala/sigmastate/lang/SigmaTyperTest.scala
- src/test/scala/sigmastate/utxo/SigmaCompilerSpecification.scala
- src/test/scala/special/sigma/SigmaDslTest.scala
> SMethod tests

- src/main/scala/org/ergoplatform/ErgoConstants.scala
- src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
- src/main/scala/sigmastate/serialization/SigmaSerializer.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/utils/SigmaByteReader.scala
- src/test/scala/sigmastate/eval/SizedTests.scala
- src/test/scala/sigmastate/serialization/DeserializationResilience.scala
> Check proposition size limit on deserialization

- src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
- src/main/scala/sigmastate/serialization/SigmaSerializer.scala
- src/main/scala/sigmastate/serialization/ValueSerializer.scala
- src/main/scala/sigmastate/utils/SigmaByteReader.scala
- src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
- src/test/scala/sigmastate/serialization/DeserializationResilience.scala
- src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
- src/test/scala/sigmastate/serialization/SerializationSpecification.scala
> Check MaxPropositionSize in reader

- src/main/scala/org/ergoplatform/validation/ValidationRules.scala
- src/main/scala/sigmastate/eval/RuntimeCosting.scala
- src/main/scala/sigmastate/interpreter/Interpreter.scala
- src/main/scala/sigmastate/serialization/DataSerializer.scala
- src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
- src/main/scala/sigmastate/serialization/TypeSerializer.scala
- src/main/scala/sigmastate/types.scala
- src/main/scala/sigmastate/utils/SigmaByteReader.scala
- src/test/scala/sigmastate/SoftForkabilitySpecification.scala
- src/test/scala/sigmastate/serialization/DeserializationResilience.scala
- src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
Also moved all validation rules into single place (ValidationRules object).
> Remove dangerous rule + more descriptions 

- src/test/scala/sigmastate/utxo/SpamSpecification.scala
Using zip and forall for RevenueSharing, fixes to TrustlessLETS and advanced tutorial.
> Protocol examples v2.1

- src/test/scala/sigmastate/CostingSpecification.scala
- src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- src/test/scala/special/sigma/SigmaDslTest.scala
> Create tests for lazy evaluation of `OR`, `AND`

- .gitignore
- build.sbt
- src/main/scala/sigmastate/serialization/DataJsonEncoder.scala
- src/main/scala/sigmastate/types.scala
- src/test/scala/sigmastate/serialization/DataJsonEncoderSpecification.scala
- src/test/scala/sigmastate/serialization/generators/ObjectGenerators.scala
> DataJsonSerializer

- docs/perf-style-guide.md
Thoroughly went through and edited the document to be reasonably clear. I did my best to not change the meaning of anything as I understood the vast majority of the points, but do check to make sure since I have only spent something alone the lines of 1 hour with scala personally.
> Proofread/edited perf-style-guide.md

- docs/perf-style-guide.md
This is doc only PR, no code should be changed.
> [doc] Scala Performance Style Guide

- .gitignore
- sigmastate/src/main/scala/org/ergoplatform/ErgoBoxAssets.scala
- sigmastate/src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- sigmastate/src/main/scala/org/ergoplatform/ErgoLikeTransaction.scala
for https://github.com/ergoplatform/ergo/pull/1071
> introduce ErgoBoxAssets

- docs/wpaper/sigma.tex
This PR fixes a couple of words in the text whitepaper about ErgoScript
> typo fixes

- common/src/main/scala/scalan/util/Extensions.scala
- sigma-api/src/main/scala/special/sigma/SigmaDsl.scala
- sigma-impl/src/main/scala/special/sigma/TestBigInt.scala
- sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
- sigmastate/src/main/scala/sigmastate/eval/Extensions.scala
- sigmastate/src/main/scala/sigmastate/eval/TreeBuilding.scala
- sigmastate/src/main/scala/sigmastate/trees.scala
- sigmastate/src/main/scala/sigmastate/utxo/transformers.scala
- sigmastate/src/test/scala/sigmastate/helpers/SigmaPPrint.scala
- sigmastate/src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslSpec.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTest.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
This PR introduces support for cross version testing for Sigma operations.
> Cross version testing support

- build.sbt
- common/src/main/scala/scalan/TypeDesc.scala
- sigma-api/src/main/scala/special/sigma/SigmaDsl.scala
- sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala
- sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
- sigmastate/src/main/scala/sigmastate/lang/Terms.scala
- sigmastate/src/main/scala/sigmastate/types.scala
- sigmastate/src/test/scala/sigmastate/CostingSpecification.scala
- sigmastate/src/test/scala/sigmastate/helpers/SigmaPPrint.scala
- sigmastate/src/test/scala/sigmastate/helpers/SigmaPPrintSpec.scala
- sigmastate/src/test/scala/sigmastate/serialization/AvlTreeSpecification.scala
- sigmastate/src/test/scala/sigmastate/serialization/generators/ObjectGenerators.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslSpec.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
- sigmastate/src/test/scala/special/sigma/SigmaTestingData.scala
This PR extends cross version testing for Sigma operations.
> Cross version testing support (part 2)

- sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
This PR prepares the test harness for full cross version test coverage of all language features.
It supports testing of:
> Refactor FeatureTest towards cross-version testing

- sigmastate/src/main/scala/sigmastate/eval/Evaluation.scala
- sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
- sigmastate/src/test/scala/sigmastate/CostingSpecification.scala
- sigmastate/src/test/scala/sigmastate/helpers/NegativeTesting.scala
- sigmastate/src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
In this release:
- added more tests
- fixed cost calculation
> Release v4.0.3

- sigmastate/src/test/scala/sigmastate/crypto/SigningSpecification.scala
The same test vectors also used in sigma-rust to check against the reference(Scala) implementation.
Corresponding sigma-rust PR - https://github.com/ergoplatform/sigma-rust/pull/226
> add Sigma AND, OR test vectors;

- build.sbt
Following codecov hack https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=2448616&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJn_oFBUJSNQDAiYNUpxg1HGpLjt5HRJaN_wlIl4LITqWZ_tlNtQZch-Fz9O6fGGPLm_Jdu9IIIkc1cfv2n-qVT5yI6ElTeOTDZnn651
Repository Action Secrets are updated as well. 
The old key is revoked.
> Use new GPG signing key for release publishing

- build.sbt
- sigmastate/src/main/scala/sigmastate/CostKind.scala
- sigmastate/src/main/scala/sigmastate/Values.scala
- sigmastate/src/main/scala/sigmastate/eval/Profiler.scala
- sigmastate/src/main/scala/sigmastate/interpreter/CostAccumulator.scala
- sigmastate/src/main/scala/sigmastate/interpreter/CostDetails.scala
- sigmastate/src/main/scala/sigmastate/interpreter/CostItem.scala
- sigmastate/src/main/scala/sigmastate/interpreter/OperationDesc.scala
- sigmastate/src/main/scala/sigmastate/lang/exceptions/Exceptions.scala
- sigmastate/src/main/scala/sigmastate/types.scala
- sigmastate/src/test/scala/sigmastate/CrossVersionProps.scala
> Preparation refactoring towards v5.0 (part 4) 

- common/src/main/java/java7/compat/Math.java
- common/src/main/scala/scalan/ExactIntegral.scala
- common/src/main/scala/scalan/ExactNumeric.scala
- library-impl/src/main/scala/special/collection/MonoidInstances.scala
- sigmastate/src/main/scala/sigmastate/Values.scala
- sigmastate/src/main/scala/sigmastate/eval/Evaluation.scala
- sigmastate/src/main/scala/sigmastate/eval/IRContext.scala
Required for https://github.com/ergoplatform/ergo-appkit/pull/100
In this PR:
> Java 7 Runtime compatibility

- build.sbt
Unused paradise and macro-compat dependencies removed in this PR
> Paradise and macro-compat dependencies removed 

- sigmastate/src/main/scala/org/ergoplatform/ErgoScriptPredef.scala
- sigmastate/src/main/scala/sigmastate/lang/SigmaCompiler.scala
- sigmastate/src/test/scala/sigmastate/lang/SigmaParserTest.scala
> Re-introduce SigmaCompiler constructor with networkPrefix

- docs/aot-jit-switch.md
- sigmastate/src/main/scala/sigmastate/interpreter/ErgoTreeEvaluator.scala
- sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
- sigmastate/src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
- sigmastate/src/main/scala/sigmastate/interpreter/ProverUtils.scala
- sigmastate/src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala
- sigmastate/src/test/scala/sigmastate/CostingSpecification.scala
- sigmastate/src/test/scala/sigmastate/CrossVersionProps.scala
- sigmastate/src/test/scala/sigmastate/ScriptVersionSwitchSpecification.scala
- sigmastate/src/test/scala/sigmastate/TestingInterpreterSpecification.scala
- sigmastate/src/test/scala/sigmastate/TestsBase.scala
- sigmastate/src/test/scala/sigmastate/helpers/ErgoTransactionValidator.scala
- sigmastate/src/test/scala/sigmastate/helpers/NegativeTesting.scala
- sigmastate/src/test/scala/sigmastate/serialization/SigSerializerSpecification.scala
- sigmastate/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
- sigmastate/src/test/scala/sigmastate/utxo/ContextEnrichingSpecification.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
> Encapsulate evaluationMode selection (towards v5.0)

- sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala
- sigmastate/src/main/scala/sigmastate/CostKind.scala
- sigmastate/src/main/scala/sigmastate/DataValueComparer.scala
- sigmastate/src/main/scala/sigmastate/SigSerializer.scala
- sigmastate/src/main/scala/sigmastate/UnprovenTree.scala
- sigmastate/src/main/scala/sigmastate/Values.scala
- sigmastate/src/main/scala/sigmastate/eval/Profiler.scala
- sigmastate/src/main/scala/sigmastate/interpreter/CostAccumulator.scala
- sigmastate/src/main/scala/sigmastate/interpreter/CostDetails.scala
- sigmastate/src/main/scala/sigmastate/interpreter/CostItem.scala
- sigmastate/src/main/scala/sigmastate/interpreter/CostingUtils.scala
- sigmastate/src/main/scala/sigmastate/interpreter/ErgoTreeEvaluator.scala
- sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
- sigmastate/src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
- sigmastate/src/main/scala/sigmastate/lang/Terms.scala
- sigmastate/src/main/scala/sigmastate/lang/exceptions/Exceptions.scala
- sigmastate/src/main/scala/sigmastate/sigmastate.scala
- sigmastate/src/main/scala/sigmastate/trees.scala
- sigmastate/src/main/scala/sigmastate/types.scala
- sigmastate/src/main/scala/sigmastate/utxo/transformers.scala
- sigmastate/src/test/scala/sigmastate/JitCostSpecification.scala
- sigmastate/src/test/scala/sigmastate/helpers/ContextEnrichingTestProvingInterpreter.scala
- sigmastate/src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
- sigmastate/src/test/scala/sigmastate/serialization/DataSerializerSpecification.scala
- sigmastate/src/test/scala/special/sigma/DataValueComparerSpecification.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
> Use JitCost type

- sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala
- sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
- sigmastate/src/test/scala/special/sigma/ContractsTestkit.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
> Finalize v5.0: fix CONTEXT.selfBoxIndex

- common/src/main/scala/sigmastate/VersionContext.scala
- library-impl/src/main/scala/special/collection/CollsOverArrays.scala
- library/src/test/scala/special/collections/CollsTests.scala
- sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
- sigmastate/src/main/scala/sigmastate/lang/SigmaBuilder.scala
- sigmastate/src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
- sigmastate/src/main/scala/sigmastate/types.scala
- sigmastate/src/test/scala/sigmastate/ErgoTreeSpecification.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
> Finalize v5.0: fix Coll.flatMap

- sigma-impl/src/main/scala/special/sigma/SigmaDslOverArrays.scala
- sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
> Finalize v5.0: fix XorOf operation (part 2)

- docs/LangSpec.md
- sigmastate/src/main/scala/sigmastate/lang/SigmaPredef.scala
- sigmastate/src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
- sigmastate/src/test/scala/sigmastate/lang/SigmaParserTest.scala
- sigmastate/src/test/scala/sigmastate/lang/SigmaTyperTest.scala
Adding fromBase16 to the frontend
> Adding fromBase16 to the frontend

- .github/workflows/ci.yml
- library-impl/src/main/scala/special/collection/Helpers.scala
> Fix RoboVM incompatibility

- sigmastate/src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- sigmastate/src/main/scala/org/ergoplatform/ErgoLikeTransaction.scala
- sigmastate/src/main/scala/org/ergoplatform/validation/SigmaValidationSettingsSerializer.scala
- sigmastate/src/main/scala/sigmastate/AvlTreeData.scala
- sigmastate/src/main/scala/sigmastate/Values.scala
- sigmastate/src/main/scala/sigmastate/serialization/BlockValueSerializer.scala
- sigmastate/src/main/scala/sigmastate/serialization/ConstantPlaceholderSerializer.scala
- sigmastate/src/main/scala/sigmastate/serialization/DataSerializer.scala
- sigmastate/src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
- sigmastate/src/main/scala/sigmastate/serialization/FuncValueSerializer.scala
- sigmastate/src/main/scala/sigmastate/serialization/ValDefSerializer.scala
- sigmastate/src/main/scala/sigmastate/serialization/ValUseSerializer.scala
- sigmastate/src/main/scala/sigmastate/serialization/transformers/SigmaTransformerSerializer.scala
- sigmastate/src/test/scala/org/ergoplatform/ErgoLikeTransactionSpec.scala
- sigmastate/src/test/scala/sigmastate/helpers/NegativeTesting.scala
- sigmastate/src/test/scala/sigmastate/serialization/DeserializationResilience.scala
Fixes #836 
Fixes #837 
This PR contains fix for Tuple in register deserialization and other potentially breaking changes in deserializers.
> Release Candidate v5.0.1

- sigmastate/src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
- sigmastate/src/test/scala/org/ergoplatform/ErgoLikeTransactionSpec.scala
> ErgoBoxCandidate.tokens does not account for same token multiple times in array

- .gitignore
- sigma-js/jest.config.js
- sigma-js/package-lock.json
- sigma-js/package.json
- sigma-js/sigmastate-js.d.ts
- sigma-js/tests/js/ErgoTree.spec.js
- sigma-js/tests/js/SigmaCompiler.spec.js
- sigma-js/tests/js/Type.spec.js
- sigma-js/tests/js/Value.spec.js
In this PR:
* Add partial type definitions for exported members;
* Disable Babel code transpilation on Jest settings for improved test performance;
* Include `package-lock.json` in version control. [That's recommended](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks#using-locked-packages) for dependency tree correctness.
> Add Sigma.JS types

- interpreter/shared/src/main/scala/sigmastate/Values.scala
- sc/shared/src/test/scala/sigmastate/ErgoTreeSpecification.scala
- sdk/js/src/main/scala/org/ergoplatform/sdk/js/ErgoTree.scala
- sigma-js/README.md
- sigma-js/package.json
- sigma-js/sigmastate-js.d.ts
- sigma-js/tests/js/ErgoTree.spec.js
> ErgoTree template

- core/shared/src/test/scala/sigma/VersionTesting.scala
- sc/shared/src/test/scala/sigma/SigmaDslSpecification.scala
- sc/shared/src/test/scala/sigmastate/ScriptVersionSwitchSpecification.scala
In this PR necessary changes made in tests due to MaxSupportedVersion is upgraded in v6.0.0
> [v6.0.0] Fix of tests due to version upgrade
